services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: local
    env_file:
      - enviroment.env
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: dockerfile-backend
    environment:
      DATABASE_NAME: local
    env_file:
      - enviroment.env
    depends_on:
      - database
    ports:
      - "8080:8080"
